filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /opt/app/logs/*
  json:
    keys_under_root: true
    add_error_key: true

processors:
  - add_tags:
      tags: ["api"]
      target: "tags"

output.logstash:
  enabled: true
  hosts: ["logstash:5045"]